name: SYNC_TEST3
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Mirror the Github organization repos to Gitee.
        id: sync
        run: |
          pwd
          ls -al
          mkdir temp_d
          cd temp_d
          git clone https://gitee.com/saintvamp/test_sync.git
          git remote -v
          ls -al
          ls -al test_sync
          cd test_sync
          git remote -v
          echo "+++++++++++++++++++++++++"
          git remote add github git@github.com:SaintVamp/test_sync.git
          echo "-------------------------"
          git remote -v
          echo "========================="

          git push github