name: Sync_Gitee
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
env:
  BRANCH_NAME: openwrt-22.03

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Init Building Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update -y
          sudo -E apt-get full-upgrade -y
          sudo -E apt-get install -y git 


      - name: Clone Source
        run: |
          cd "/home/runner"
          git clone git@gitee.com:saintvamp/SVTOOL.git "SVTOOL"
          sudo chown -R runner:runner "SVTOOL"
          cd "/home/runner/SVTOOL"
          git remote add github git@github.com:SaintVamp/SVTOOL.git
          git pull github master:master
