name: SYNC_TEST3
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Mirror the Github organization repos to Gitee.
        id: sync
        run: |
          ls -al /home/runner/work/syncGitee/syncGitee
