name: SYNC_TEST3
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Mirror the Github organization repos to Gitee.
        id: sync
        run: |
          pwd
          ls /home/runner
          mkdir /home/runner/.ssh
          curl -o /home/runner/.ssh/id_rsa https://raw.githubusercontent.com/SaintVamp/syncGitee/master/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ls /home/runner/.ssh
          echo "===========1==========="
          cd /home/runner/
          mkdir temp_d
          cd /home/runner/temp_d
          mkdir github
          cd github
          pwd
          #          git init
          git clone https://github.com/SaintVamp/test_sync.git
          # ls
          # ls -al test_sync
          ls -al test_sync/.git
          echo "===========2==========="
          cd /home/runner/temp_d
          mkdir gitee
          cd gitee
          pwd
          # git init
          git clone https://gitee.com/saintvamp/test_sync.git
          # git remote -v
          # ls
          # ls -al test_sync
          ls -al test_sync/.git
          rm -rf .git
          echo "===========3==========="
          cp -r /home/runner/temp_d/gitee/test_sync/ /home/runner/temp_d/github/test_sync/
          cd /home/runner/temp_d/github/test_sync
          ls -al .git
          git remote -v
          pwd
          echo "===========4==========="
          cd /home/runner/temp_d/github/
          git rm --cached test_sync
          git submodule add https://github.com/SaintVamp/test_sync.git test_sync
          git add -v .
          echo "===========5==========="
          git status
          echo "===========6==========="
          git commit
          git pull
          #          cd test_sync
          #          git remote -v
          #          echo "+++++++++++++++++++++++++"
          #          git remote add github
          #          echo "-------------------------"
          #          git remote -v
          #          echo "========================="
          #          git push github
