name: sync_every_hour
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Mirror the Github organization repos to Gitee.
        id: sync
        run: |
          sh /home/runner/work/syncGitee/syncGitee/init-rss.sh
          sh /home/runner/work/syncGitee/syncGitee/sync.sh py_qbRssDown
          sh /home/runner/work/syncGitee/syncGitee/sync.sh py_book
          sh /home/runner/work/syncGitee/syncGitee/sync.sh nginx_conf
          sh /home/runner/work/syncGitee/syncGitee/sync.sh nassyncswitch

          
