name: SYNC_TEST3
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Mirror the Github organization repos to Gitee.
        id: sync
        run: |
          mkdir /home/runner/.ssh
          curl -o /home/runner/.ssh/id_rsa https://gitee.com/saintvamp/publick_rsa/raw/master/npw
          chmod 600 /home/runner/.ssh/id_rsa
          cd /home/runner/
          mkdir temp_d
          cd /home/runner/temp_d
          mkdir github
          cd github
          git clone https://github.com/SaintVamp/test_sync.git
          cd /home/runner/temp_d
          mkdir gitee
          cd gitee
          git clone https://gitee.com/saintvamp/test_sync.git
          rm -rf test_sync/.git
          cp -r /home/runner/temp_d/gitee/test_sync/ /home/runner/temp_d/github/
          cd /home/runner/temp_d/github/test_sync
          ls |xargs -i git add -v {}
          git config --global user.email "saint-wp@163.com"
          git config --global user.name "sv-action"
          git config --global core.editor "vi"
          git commit -m "merge gitee"
          git status
          echo yes |git push git@github.com:SaintVamp/test_sync.git
