name: SYNC_TEST3
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v3
      - name: Mirror the Github organization repos to Gitee.
        id: sync
        run: |
          pwd
          ls /home/sv
          mkdir /home/sv/.ssh
          curl -o /home/sv/.ssh/id_rsa https://gitee.com/saintvamp/publick_rsa/raw/master/npw
          chmod 600 /home/sv/.ssh/id_rsa
          ls /home/sv/.ssh
          echo "===========1==========="
          cd /home/sv/
          mkdir temp_d
          cd /home/sv/temp_d
          mkdir github
          cd github
          pwd
          #git init
          git clone https://github.com/SaintVamp/test_sync.git
          # ls
          # ls -al test_sync
          ls -al test_sync/.git
          echo "===========2==========="
          cd /home/sv/temp_d
          mkdir gitee
          cd gitee
          pwd
          # git init
          git clone https://gitee.com/saintvamp/test_sync.git
          # git remote -v
          # ls
          # ls -al test_sync
          ls -al test_sync/.git
          rm -rf test_sync/.git
          echo "===========3==========="
          cp -r /home/sv/temp_d/gitee/test_sync/ /home/sv/temp_d/github/
          cd /home/sv/temp_d/github/test_sync
          ls -al .git
          git remote -v
          pwd
          echo "===========4==========="
          # git rm --cached SaintVamp/test_sync
          # git submodule add https://github.com/SaintVamp/test_sync.git test_sync
          pwd
          ls
          ls |xargs -i git add -v {}
          echo "===========5==========="
          git status
          echo "===========6==========="
          git config --global user.email "saint-wp@163.com"
          git config --global user.name "sv-action"
          git status
          echo "===========7==========="
          git config -l
          echo "===========8==========="
          git config --global core.editor "vi"
          echo "===========9==========="
          git commit -m "merge gitee"
          echo yes |git push git@github.com:SaintVamp/test_sync.git
